name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deliver:
    if: "!contains(github.event.head_commit.message, 'CD: update model artifact')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Adult dataset
        run: |
          curl -o data/raw/adult.data https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
          curl -o data/raw/adult.test https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test
      
      - name: Train and save model
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
          EXPERIMENT_NAME: ${{vars.EXPERIMENT_NAME}}
          MLFLOW_URL: ${{vars.MLFLOW_URL}}
        run: |
          python src/train.py

