name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deliver:
    if: "!contains(github.event.head_commit.message, 'CD: update model artifact')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train and save model
        run: |
          python model/train.py
          python -c "import joblib; import model.train as t; X_train, X_test, y_train, y_test = t.load_data(); m = t.train_model(X_train, y_train); joblib.dump(m, 'model.joblib')"

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.joblib
          
      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          
      - name: Run latency test on saved model
        run: |
          PYTHONPATH=. pytest it/latency_check.py --capture=tee-sys
          
      - name: Commit updated model to main (trigger Render deploy)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull origin main
          git add model.joblib
          git commit -m "CD: update model artifact" || echo "Nothing to commit"
          git push origin main